### ISSUE TITLE
Can't run ng serve

### ISSUE THREAD

**Issue by jarrettj** [ultrasonicsoft/gmap-geolocation-demo#1]
Hi,

Good day.

When running ng serve:
```
$ ng serve
Local workspace file ('angular.json') could not be found.
```

Regards.
JJ

**Comment by ultrasonicsoft** [comment]
Hi,
Are you running Ng serve command in correct directory? Make sure current
directory has angular.json file.

**Comment by jarrettj** [comment]
This is weird, I did a git clone and there is no angular.json ???

<img width="794" alt="screen shot 2018-09-21 at 08 13 36" src="https://user-images.githubusercontent.com/777547/45863458-8762f480-bd76-11e8-85f0-8c79dc6d3c89.png">

**Comment by jarrettj** [comment]
No worries, copied paste from your example worked. No need to run demo. Thanks!

Regards. 
JJ
